--Janessa Reed
--Final DDL
--03/25/2025

-- Creating Students Table
CREATE TABLE STUDENTS (
    Student_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Bus_Rider CHAR(1) CHECK (Bus_Rider IN ('Y', 'N')),  -- Maps Boolean (Yes/No)
    After_School_Days VARCHAR2(100) -- Stores days in comma-separated format
);

-- Creating Authorized Adults Table
CREATE TABLE AUTHORIZED_ADULTS (
    Adult_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Relationship VARCHAR2(50) NOT NULL,
    Pickup_Days VARCHAR2(100) -- Stores days in comma-separated format
);

-- Creating Organizations Table
CREATE TABLE ORGANIZATIONS (
    Org_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Organization_Name VARCHAR2(100) NOT NULL,
    Pickup_Days VARCHAR2(100) -- Stores days in comma-separated format
);

-- Creating Student Pickup Table
CREATE TABLE STUDENT_PICKUP (
  / Record_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   /Student_ID NUMBER NOT NULL,
    Pickup_Date DATE NOT NULL,
    Pickup_Type VARCHAR2(10) CHECK (Pickup_Type IN ('Adult', 'Organization', 'Bus')),
    Adult_ID NUMBER NULL,  -- Nullable since an organization might pick up instead
    Org_ID NUMBER NULL,  -- Nullable since an adult might pick up instead
    FOREIGN KEY (Student_ID) REFERENCES STUDENTS(Student_ID) ON DELETE CASCADE,
    FOREIGN KEY (Adult_ID) REFERENCES AUTHORIZED_ADULTS(Adult_ID) ON DELETE SET NULL,
    FOREIGN KEY (Org_ID) REFERENCES ORGANIZATIONS(Org_ID) ON DELETE SET NULL
);

-- Creating Student-Adult Relationship Table (Many-to-Many)
CREATE TABLE STUDENT_ADULT_RELATION (
    Student_ID NUMBER NOT NULL,
    Adult_ID NUMBER NOT NULL,
    PRIMARY KEY (Student_ID, Adult_ID),
    FOREIGN KEY (Student_ID) REFERENCES STUDENTS(Student_ID) ON DELETE CASCADE,
    FOREIGN KEY (Adult_ID) REFERENCES AUTHORIZED_ADULTS(Adult_ID) ON DELETE CASCADE
);

-- Creating Student-Organization Relationship Table (Many-to-Many)
CREATE TABLE STUDENT_ORG_RELATION (
    Student_ID NUMBER NOT NULL,
    Org_ID NUMBER NOT NULL,
    PRIMARY KEY (Student_ID, Org_ID),
    FOREIGN KEY (Student_ID) REFERENCES STUDENTS(Student_ID) ON DELETE CASCADE,
    FOREIGN KEY (Org_ID) REFERENCES ORGANIZATIONS(Org_ID) ON DELETE CASCADE
);

-- Creating Indexes for Optimization
CREATE INDEX idx_student_id ON STUDENT_PICKUP(Student_ID);
CREATE INDEX idx_adult_id ON STUDENT_PICKUP(Adult_ID);
CREATE INDEX idx_org_id ON STUDENT_PICKUP(Org_ID);
CREATE INDEX idx_pickup_date ON STUDENT_PICKUP (Pickup_Date);
CREATE INDEX idx_bus_rider ON STUDENTS (Bus_Rider);
CREATE INDEX idx_after_school_days ON STUDENTS (After_School_Days);

-- Sample Data Insertion
INSERT INTO STUDENTS (First_Name, Last_Name, Bus_Rider, After_School_Days) VALUES ('John', 'Doe', 'Y', 'Monday, Wednesday');
INSERT INTO STUDENTS (First_Name, Last_Name, Bus_Rider, After_School_Days) VALUES ('Jane', 'Smith', 'N', 'Tuesday, Thursday');

INSERT INTO AUTHORIZED_ADULTS (First_Name, Last_Name, Relationship, Pickup_Days) VALUES ('Mary', 'Doe', 'Mother', 'Monday, Wednesday');
INSERT INTO AUTHORIZED_ADULTS (First_Name, Last_Name, Relationship, Pickup_Days) VALUES ('Robert', 'Smith', 'Father', 'Tuesday, Thursday');

INSERT INTO ORGANIZATIONS (Organization_Name, Pickup_Days) VALUES ('YMCA', 'Monday, Wednesday');
INSERT INTO ORGANIZATIONS (Organization_Name, Pickup_Days) VALUES ('Kids Robotics Academy', 'Friday');

-- Relating Students to Adults
INSERT INTO STUDENT_ADULT_RELATION (Student_ID, Adult_ID) VALUES (1, 1);
INSERT INTO STUDENT_ADULT_RELATION (Student_ID, Adult_ID) VALUES (2, 2);

-- Relating Students to Organizations
INSERT INTO STUDENT_ORG_RELATION (Student_ID, Org_ID) VALUES (1, 1);
INSERT INTO STUDENT_ORG_RELATION (Student_ID, Org_ID) VALUES (2, 2);

-- Sample Pickup Records
INSERT INTO STUDENT_PICKUP (Student_ID, Pickup_Date, Pickup_Type, Adult_ID, Org_ID) VALUES (1, TO_DATE('2025-02-07', 'YYYY-MM-DD'), 'Adult', 1, NULL);
INSERT INTO STUDENT_PICKUP (Student_ID, Pickup_Date, Pickup_Type, Adult_ID, Org_ID) VALUES (2, TO_DATE('2025-02-07', 'YYYY-MM-DD'), 'Organization', NULL, 2);

COMMIT;

-- Insert data into STUDENTS
INSERT INTO STUDENTS (First_Name, Last_Name, Bus_Rider, After_School_Days)
VALUES ('Alice', 'Smith', 'N', 'Monday, Wednesday');

INSERT INTO STUDENTS (First_Name, Last_Name, Bus_Rider, After_School_Days)
VALUES ('Bob', 'Johnson', 'Y', 'Tuesday, Thursday');

INSERT INTO STUDENTS (First_Name, Last_Name, Bus_Rider, After_School_Days)
VALUES ('Charlie', 'Brown', 'N', 'Monday, Friday');

INSERT INTO STUDENTS (First_Name, Last_Name, Bus_Rider, After_School_Days)
VALUES ('John', 'Doe', 'N', 'Monday, Wednesday');

COMMIT;

-- Insert data into AUTHORIZED_ADULTS
INSERT INTO AUTHORIZED_ADULTS (First_Name, Last_Name, Relationship, Pickup_Days)
VALUES ('Sarah', 'Miller', 'Mother', 'Monday, Wednesday');

INSERT INTO AUTHORIZED_ADULTS (First_Name, Last_Name, Relationship, Pickup_Days)
VALUES ('Michael', 'Davis', 'Father', 'Tuesday, Thursday');

INSERT INTO AUTHORIZED_ADULTS (First_Name, Last_Name, Relationship, Pickup_Days)
VALUES ('Emily', 'Clark', 'Guardian', 'Friday');

COMMIT;

-- Insert data into ORGANIZATIONS
INSERT INTO ORGANIZATIONS (Organization_Name, Pickup_Days)
VALUES ('YMCA', 'Monday, Friday');

INSERT INTO ORGANIZATIONS (Organization_Name, Pickup_Days)
VALUES ('Kumon Math Center', 'Tuesday, Thursday');

INSERT INTO ORGANIZATIONS (Organization_Name, Pickup_Days)
VALUES ('Kids Robotics Academy', 'Wednesday');

INSERT INTO ORGANIZATIONS (Organization_Name, Pickup_Days)
VALUES ('After School Art Club', 'Monday, Wednesday');

COMMIT;

-- Insert data into STUDENT_PICKUP
INSERT INTO STUDENT_PICKUP (Student_ID,Pickup_Date, Pickup_Type, Adult_ID, Org_ID)
VALUES (1, TO_DATE('2025-02-07', 'YYYY-MM-DD'), 'Adult', 1, NULL);

INSERT INTO STUDENT_PICKUP (Student_ID, Pickup_Date, Pickup_Type, Adult_ID, Org_ID)
VALUES (2, TO_DATE('2025-02-07', 'YYYY-MM-DD'), 'Organization', NULL, 2);

INSERT INTO STUDENT_PICKUP (Student_ID, Pickup_Date, Pickup_Type, Adult_ID, Org_ID)
VALUES (3, TO_DATE('2025-02-07', 'YYYY-MM-DD'), 'Adult', 3, NULL);

INSERT INTO STUDENT_PICKUP (Student_ID, Pickup_Date, Pickup_Type, Adult_ID, Org_ID)
VALUES (4, TO_DATE('2025-02-07', 'YYYY-MM-DD'), 'Organization', NULL, 4);

COMMIT;
